version: '3'
services:
  go:
    image: fiber-golang-api-server-image
    container_name: fiber-golang-api-server-container
    build:
      context: .
      dockerfile: container/golang/Dockerfile
    command: ${GOLANG_COMMAND}
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./src:/app
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env
    ports:
      - ${GOLANG_PORT}
      - ${AIR_TOML_PORT}

  db:
    image: mysql:5.7
    container_name: database-fiber-golang-container # phpMyAdminサービスのPMA_HOSTSに設定する
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'
      LC_ALL: 'ja_JP.UTF-8'
      LANG: "ja_JP.UTF-8"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./container/db/data:/var/lib/mysql
      - ./container/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
